# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import GRPC_pb2 as GRPC__pb2


class numberFlightsStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.getNumberFlights = channel.unary_unary(
                '/numFlights.numberFlights/getNumberFlights',
                request_serializer=GRPC__pb2.numberFlightsRequest.SerializeToString,
                response_deserializer=GRPC__pb2.numberFlightsResponse.FromString,
                )


class numberFlightsServicer(object):
    """Missing associated documentation comment in .proto file."""

    def getNumberFlights(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_numberFlightsServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'getNumberFlights': grpc.unary_unary_rpc_method_handler(
                    servicer.getNumberFlights,
                    request_deserializer=GRPC__pb2.numberFlightsRequest.FromString,
                    response_serializer=GRPC__pb2.numberFlightsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'numFlights.numberFlights', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class numberFlights(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def getNumberFlights(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/numFlights.numberFlights/getNumberFlights',
            GRPC__pb2.numberFlightsRequest.SerializeToString,
            GRPC__pb2.numberFlightsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
