openapi: 3.0.0
info:
  version: 1.0.0
  title: USA Flights API
  description: This API allows the user to obtain information and statistics flights that occured in 2020, 2021 and 2022. It also allows users to forecast future flights with this data. Plus, admins can add new flights, update flight information and delete existing ones.
tags:
  - name: flights
    description: Obtain information about flights and get flight forecasts
  - name: airlines
    description: Obtain information about airlines and their reliability
  - name: admin
    description: Add a new flight and update or delete an existing one
paths:
  /flights/statistics:
    get:
      tags:
        - flights
      summary: Obtain statistics regarding flights
      description: Obtain flight statistics, given certain criteria.
      operationId: getFlightsStatistics
      parameters:
        - name: limit
          in: query
          description: Limit the number of results
          required: false
          schema:
            type: integer
            format: int32
        - name: airline-code
          in: query
          description: Filter results by airlines
          required: false
          schema:
            type: string
        - name: origin-airport-id
          in: query
          description: Filter results by the origin airport
          required: false
          schema:
            type: integer
            format: int32
        - name: dest-airport-id
          in: query
          description: Filter results by the destination airport
          required: false
          schema:
            type: integer
            format: int32
        - name: start-date
          in: query
          description: Filter results with a flight date after the given date
          required: false
          schema:
            type: integer
            format: date
        - name: end-date
          in: query
          description: Filter results with a flight date before the given date
          required: false
          schema:
            type: integer
            format: date
      responses: 
        '200':
          description: Successful Operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  statistics:
                    $ref: '#/components/schemas/FlightsStatistics'
        '400':
          description: Invalid Parameters
  /flights:
    get:
      tags:
        - flights
      summary: Obtain flight data by flight number
      description: Obtain the details of a flight, given the necessary details
      operationId: getFlightByNumber
      parameters:
        - name: airline-code
          in: query
          description: Airline code for the airline that performed the flight
          required: true
          schema:
            type: string
        - name: origin-airport-id
          in: query
          description: Origin airport id of flight
          required: true
          schema:
            type: integer
            format: int32
        - name: dest-airport-id
          in: query
          description: Destination airport id of flight
          required: false
          schema:
            type: integer
            format: int32
        - name: flight-date
          in: query
          description: Flight date
          required: true
          schema:
            type: integer
            format: date
        - name: flight-number
          in: query
          description: Flight number
          required: true
          schema:
            type: integer
            format: date
      responses:
        '200':
          description: Successful Operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Flight'
        '400':
          description: Invalid Flight Number
        '404':
          description: Flight Not Found
      
  /flights/forecast:
    get:
      tags:
        - flights
      summary: Obtain a forecast for a future flight
      description: Obtain predictions for a future flight, given a date and other details
      operationId: getFlightForecast
      parameters:
        - name: flight-date
          in: query
          description: Date for future flight
          required: true
          schema:
            type: string
            format: date
        - name: airline-code
          in: query
          description: Airline for future flight
          required: true
          schema:
            type: string
        - name: origin-airport-id
          in: query
          description: Origin airport for future flight
          required: true
          schema:
            type: integer
            format: int32
        - name: dest-airport-id
          in: query
          description: Destination airport for future flight
          required: true
          schema:
            type: integer
            format: int32
        - name: departure-time
          in: query
          description: Departure time for future flight
          required: true
          schema:
            type: integer
            format: time
        - name: arrival-time
          in: query
          description: Arrival time for future flight
          required: true
          schema:
            type: integer
            format: time
      responses:
        '200':
          description: Successful Operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FlightPrediction'
        '400':
          description: Invalid Parameters
  /airlines/{airline-code}:
    get:
      tags:
        - airlines
      summary: Obtain airline data by airline code
      description: Obtain airline data given an airline code
      operationId: getAirlineByCode
      parameters:
        - name: airline-code
          in: path
          description: Unique carrier code of the airline to return
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful Operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Airline'
        '400':
          description: Invalid Airline Code
        '404':
          description: Airline Not Found
  /airlines/rank:
    get:
      tags:
        - airlines
      summary: Obtain airline ranks
      description: Obtain airline ranks, given weights and specifications for calculating it
      operationId: getAirlineRanks
      parameters:
        - name: limit
          in: query
          description: Limit the number of results
          required: false
          schema:
            type: integer
            format: int32
        - name: cancellation-weight
          in: query
          description: Weight of cancellations in calculating the airline rank
          required: false
          schema:
            type: integer
            format: int32
            minimum: 0
            maximum: 100
        - name: diversion-weight
          in: query
          description: Weight of diversions in calculating the airline rank
          required: false
          schema:
            type: integer
            format: int32
            minimum: 0
            maximum: 100
        - name: delay-weight
          in: query
          description: Weight of delays in calculating the airline rank
          required: false
          schema:
            type: integer
            format: int32
            minimum: 0
            maximum: 100
        - name: airline-code
          in: query
          description: Rank the given airline
          required: false
          schema:
            type: string
        - name: origin-airport-id
          in: query
          description: Rank airlines using flight data from this origin airport
          required: false
          schema:
            type: integer
            format: int32
        - name: dest-airport-id
          in: query
          description: Rank airlines using flight data from this destination airport
          required: false
          schema:
            type: integer
            format: int32
        - name: start-date
          in: query
          description: Rank airlines using flight data after the given date
          required: false
          schema:
            type: integer
            format: date
        - name: end-date
          in: query
          description: Rank airlines using flight data before the given date
          required: false
          schema:
            type: integer
            format: date
      responses:
        '200':
          description: Successful Operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/AirlineRank'
  /admin/flights:
    post:
      tags:
        - admin
      summary: Add a new flight
      description: The admin can add a new flight and its information
      operationId: postFlight
      requestBody:
        description: Add a new flight
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Flight'
        required: true
      responses:
        '200':
          description: Successful Operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Flight'
        '405':
          description: Invalid input
  /admin/flights/{flight-number}:
    put:
      tags:
        - admin
      summary: Update an existing flight
      description: The admin can update an existing flight's information by its flight number
      operationId: putFlight
      parameters:
        - name: flight-number
          description: Number of the flight to update
          in: path
          required: true
          schema:
            type: integer
            format: int32
      requestBody:
        description: Update an existing flight
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Flight'
        required: true
      responses:
        '200':
          description: Successful Operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Flight'
        '404':
          description: Flight not Found
        '405':
          description: Invalid input
    delete:
      tags:
        - admin
      summary: Delete an existing flight
      description: The admin can delete an existing flight by its flight number
      operationId: deleteFlight
      parameters:
        - name: flight-number
          description: Number of the flight to delete
          in: path
          required: true
          schema:
            type: integer
            format: int32
      responses:
        '204':
          description: Successful Deletion
        '404':
          description: Flight not Found
        '405':
          description: Invalid input
components:
  schemas:
    Flight:
      type: object
      properties:
        flightDate:
          type: string
          format: date
        flightNumber:
          type: integer
          format: int32
        flightDuration:
          type: integer
          format: int32
        cancelled:
          type: boolean
        diverted:
          type: boolean
        tailNumber:
          type: string
        airlineCode:
          type: string
        departure:
          $ref: '#/components/schemas/FlightLandOrDep'
        arrival:
          $ref: '#/components/schemas/FlightLandOrDep'
          
    Airline:
      type: object
      properties:
        name:
          type: string
        code:
          type: string
        iata:
          type: string
        icao:
          type: string
          
    AirlineRank:
      type: object
      properties:
        rankScore:
          type: integer
          format: int32
          minimum: 0
          maximum: 100
        airline:
          $ref: '#/components/schemas/Airline'
        statistics:
          $ref: '#/components/schemas/FlightsStatistics'
          
    FlightLandOrDep:
      type: object
      properties:
        airportId:
          type: integer
          format: int32
        scheduled:
          type: integer
          format: time
        actual:
          type: integer
          format: time
        delay:
          type: integer
          format: int32
    FlightPrediction:
      type: object
      properties:
        cancellingProbability:
          type: number
          format: float
          minimum: 0
          maximum: 1
        divertingProbability:
          type: number
          format: float
          minimum: 0
          maximum: 1
        expectedDelay:
          type: integer
          format: int32
          
    FlightsStatistics:
      type: object
      properties:
        total_flights:
          type: integer
          format: int64
        average_delay:
          type: number
          format: float
        max_delay:
          type: integer
          format: int32
        cancellation_percentage:
          type: number
          format: float
          minimum: 0
          maximum: 100
        diversion_percentage:
          type: number
          format: float
          minimum: 0
          maximum: 100