# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.airline import Airline  # noqa: F401,E501
from swagger_server.models.flights_statistics import FlightsStatistics  # noqa: F401,E501
from swagger_server import util


class AirlineRank(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, rank_score: int=None, airline: Airline=None, statistics: FlightsStatistics=None):  # noqa: E501
        """AirlineRank - a model defined in Swagger

        :param rank_score: The rank_score of this AirlineRank.  # noqa: E501
        :type rank_score: int
        :param airline: The airline of this AirlineRank.  # noqa: E501
        :type airline: Airline
        :param statistics: The statistics of this AirlineRank.  # noqa: E501
        :type statistics: FlightsStatistics
        """
        self.swagger_types = {
            'rank_score': int,
            'airline': Airline,
            'statistics': FlightsStatistics
        }

        self.attribute_map = {
            'rank_score': 'rankScore',
            'airline': 'airline',
            'statistics': 'statistics'
        }
        self._rank_score = rank_score
        self._airline = airline
        self._statistics = statistics

    @classmethod
    def from_dict(cls, dikt) -> 'AirlineRank':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The AirlineRank of this AirlineRank.  # noqa: E501
        :rtype: AirlineRank
        """
        return util.deserialize_model(dikt, cls)

    @property
    def rank_score(self) -> int:
        """Gets the rank_score of this AirlineRank.


        :return: The rank_score of this AirlineRank.
        :rtype: int
        """
        return self._rank_score

    @rank_score.setter
    def rank_score(self, rank_score: int):
        """Sets the rank_score of this AirlineRank.


        :param rank_score: The rank_score of this AirlineRank.
        :type rank_score: int
        """

        self._rank_score = rank_score

    @property
    def airline(self) -> Airline:
        """Gets the airline of this AirlineRank.


        :return: The airline of this AirlineRank.
        :rtype: Airline
        """
        return self._airline

    @airline.setter
    def airline(self, airline: Airline):
        """Sets the airline of this AirlineRank.


        :param airline: The airline of this AirlineRank.
        :type airline: Airline
        """

        self._airline = airline

    @property
    def statistics(self) -> FlightsStatistics:
        """Gets the statistics of this AirlineRank.


        :return: The statistics of this AirlineRank.
        :rtype: FlightsStatistics
        """
        return self._statistics

    @statistics.setter
    def statistics(self, statistics: FlightsStatistics):
        """Sets the statistics of this AirlineRank.


        :param statistics: The statistics of this AirlineRank.
        :type statistics: FlightsStatistics
        """

        self._statistics = statistics
