# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.flights_statistics import FlightsStatistics  # noqa: F401,E501
from swagger_server import util


class InlineResponse200(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, statistics: FlightsStatistics=None):  # noqa: E501
        """InlineResponse200 - a model defined in Swagger

        :param statistics: The statistics of this InlineResponse200.  # noqa: E501
        :type statistics: FlightsStatistics
        """
        self.swagger_types = {
            'statistics': FlightsStatistics
        }

        self.attribute_map = {
            'statistics': 'statistics'
        }
        self._statistics = statistics

    @classmethod
    def from_dict(cls, dikt) -> 'InlineResponse200':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The inline_response_200 of this InlineResponse200.  # noqa: E501
        :rtype: InlineResponse200
        """
        return util.deserialize_model(dikt, cls)

    @property
    def statistics(self) -> FlightsStatistics:
        """Gets the statistics of this InlineResponse200.


        :return: The statistics of this InlineResponse200.
        :rtype: FlightsStatistics
        """
        return self._statistics

    @statistics.setter
    def statistics(self, statistics: FlightsStatistics):
        """Sets the statistics of this InlineResponse200.


        :param statistics: The statistics of this InlineResponse200.
        :type statistics: FlightsStatistics
        """

        self._statistics = statistics
