apiVersion: apps/v1
kind: Deployment
metadata:
  name: flight-d
  labels:
    app: flight
spec:
  replicas: 3
  selector:
    matchLabels:
      app: flight
  template:
    metadata:
      labels:
        app: flight
    spec:
      containers:
        - name: flight
          image: therobertsan/flight-container:v2
          ports:
            - containerPort: 5000
          env:
            - name: API_TOKEN
              valueFrom:
                secretKeyRef:
                  name: my-secret
                  key: API_TOKEN 
---
apiVersion: v1
kind: Service
metadata:
  name: flight-s-n
  labels:
    app: flight
spec:
  type: NodePort
  selector:
    app: flight
  ports:
    - name: http
      protocol: TCP
      port: 5000
      nodePort: 30002
      targetPort: 5000
