apiVersion: apps/v1
kind: Deployment
metadata:
  name: predict-d
  labels:
    app: predict
spec:
  replicas: 3
  selector:
    matchLabels:
      app: predict
  template:
    metadata:
      labels:
        app: predict
    spec:
      containers:
        - name: predict
          image: jbrazf/predict:v1.0
          ports:
            - containerPort: 8080
          env:
            - name: API_TOKEN
              valueFrom:
                secretKeyRef:
                  name: my-secret
                  key: API_TOKEN
---
apiVersion: v1
kind: Service
metadata:
  name: predict-s-n
  labels:
    app: predict
spec:
  type: NodePort
  selector:
    app: predict
  ports:
    - name: http
      protocol: TCP
      port: 8080
      nodePort: 30004
      targetPort: 8080
