apiVersion: apps/v1
kind: Deployment
metadata:
  name: ranking-d
  labels:
    app: ranking
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ranking
  template:
    metadata:
      labels:
        app: ranking
    spec:
      containers:
        - name: ranking
          image: selous1/ranking:v1.0
          ports:
            - containerPort: 5000
          env:
            - name: API_TOKEN
              valueFrom:
                secretKeyRef:
                  name: my-secret
                  key: API_TOKEN
---
apiVersion: v1
kind: Service
metadata:
  name: ranking-s-n
  labels:
    app: ranking
spec:
  type: NodePort
  selector:
    app: ranking
  ports:
    - name: http
      protocol: TCP
      port: 5000
      nodePort: 30003
      targetPort: 5000
