apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin-d
  labels:
    app: admin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: admin
  template:
    metadata:
      labels:
        app: admin
    spec:
      containers:
        - name: admin
          image: selous1/admin:v1.1
          ports:
            - containerPort: 5005
          env:
            - name: API_TOKEN
              valueFrom:
                secretKeyRef:
                  name: my-secret
                  key: API_TOKEN
            - name: TABLE_NAME
              valueFrom:
                configMapKeyRef:
                  name: my-configmap
                  key: table 
---
apiVersion: v1
kind: Service
metadata:
  name: admin-s
  labels:
    app: admin
spec:
  selector:
    app: admin
  #clusterIP: None
  type: NodePort
  ports:
    - name: http
      protocol: TCP
      port: 5000
      targetPort: 5005
      nodePort: 30005
