apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin-d
  labels:
    app: admin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: admin
  template:
    metadata:
      labels:
        app: admin
    spec:
      containers:
        - name: admin
          image: santig007/cnproject:admin1.0
          livenessProbe:
            httpGet:
              path: /
              port: 5000
            initialDelaySeconds: 3
            periodSeconds: 3
          ports:
            - containerPort: 5000
          env:
            - name: API_TOKEN
              valueFrom:
                secretKeyRef:
                  name: my-secret
                  key: API_TOKEN
            - name: TABLE_NAME
              valueFrom:
                configMapKeyRef:
                  name: my-configmap
                  key: table
---
apiVersion: v1
kind: Service
metadata:
  name: admin-s
  labels:
    app: admin
spec:
  selector:
    app: admin
  #clusterIP: None
  ports:
    - name: http
      protocol: TCP
      port: 5000
      targetPort: 5000
