apiVersion: apps/v1
kind: Deployment
metadata:
  name: airline-d
  labels:
    app: airline
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: "/metrics"
    prometheus.io/port: "8080" 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: airline
  template:
    metadata:
      labels:
        app: airline
    spec:
      serviceAccountName: airline-service-account
      containers:
        - name: airline
          image: selous1/airlines:v1.0
          ports:
            - containerPort: 5000
          env:
            - name: API_TOKEN
              valueFrom:
                secretKeyRef:
                  name: my-secret
                  key: API_TOKEN 
            - name: TABLE_NAME
              valueFrom:
                configMapKeyRef:
                  name: my-configmap
                  key: table
---
apiVersion: v1
kind: Service
metadata:
  name: airline-s
  labels:
    app: airline
spec:
  type: NodePort
  selector:
    app: airline
  #clusterIP: None
  ports:
    - name: http
      protocol: TCP
      port: 5000
      nodePort: 30001
      targetPort: 5000