apiVersion: apps/v1
kind: Deployment
metadata:
  name: flight-d
  labels:
    app: flight
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flight
  template:
    metadata:
      labels:
        app: flight
    spec:
      containers:
        - name: flight
          image: santig007/cnproject:flights1.0
          ports:
            - containerPort: 5000
          env:
            - name: API_TOKEN
              valueFrom:
                secretKeyRef:
                  name: my-secret
                  key: API_TOKEN 
            - name: TABLE_NAME
              valueFrom:
                configMapKeyRef:
                  name: my-configmap
                  key: table
---
apiVersion: v1
kind: Service
metadata:
  name: flight-s
  labels:
    app: flight
spec:
  selector:
    app: flight
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 5000
    - name: grpc
      protocol: TCP
      port: 50051
      targetPort: 50051
