apiVersion: apps/v1
kind: Deployment
metadata:
  name: predict-d
  labels:
    app: predict
spec:
  replicas: 3
  selector:
    matchLabels:
      app: predict
  template:
    metadata:
      labels:
        app: predict
    spec:
      containers:
        - name: predict
          image: jbrazf/predict:v1.0
          ports:
            - containerPort: 5000
          env:
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: aws-secret
                  key: AWS_ACCESS_KEY_ID
            - name: AWS_ACCESS_KEY_SECRET
              valueFrom:
                secretKeyRef:
                  name: aws-secret
                  key: AWS_ACCESS_KEY_SECRET
            - name: AWS_REGION
              valueFrom:
                configMapKeyRef:
                  name: my-configmap
                  key: prediction_aws_region
            - name: AWS_FUNCTION_NAME
              valueFrom:
                configMapKeyRef:
                  name: my-configmap
                  key: prediction_function_name
---
apiVersion: v1
kind: Service
metadata:
  name: predict-s
  labels:
    app: predict
spec:
  selector:
    app: predict
  #clusterIP: None
  ports:
    - name: http
      protocol: TCP
      port: 5000
      targetPort: 5000
