apiVersion: apps/v1
kind: Deployment
metadata:
  name: predict-d
  labels:
    app: predict
spec:
  replicas: 1
  selector:
    matchLabels:
      app: predict
  template:
    metadata:
      labels:
        app: predict
    spec:
      containers:
        - name: predict
          image: jbrazf/predict:v1.0
          ports:
            - containerPort: 8080
          env:
            - name: API_TOKEN
              valueFrom:
                secretKeyRef:
                  name: my-secret
                  key: API_TOKEN
            - name: TABLE_NAME
              valueFrom:
                configMapKeyRef:
                  name: my-configmap
                  key: table
---
apiVersion: v1
kind: Service
metadata:
  name: predict-s
  labels:
    app: predict
spec:
  selector:
    app: predict
  ports:
    - name: http
      protocol: TCP
      port: 5000
      targetPort: 8080
