apiVersion: apps/v1
kind: Deployment
metadata:
  name: ranking-d
  labels:
    app: ranking
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ranking
  template:
    metadata:
      labels:
        app: ranking
    spec:
      containers:
        - name: ranking
          image: selous1/ranking:v1.5
          resources:
            requests:
              memory: "260Mi"
          ports:
            - containerPort: 5000
          env:
            - name: API_TOKEN
              valueFrom:
                secretKeyRef:
                  name: my-secret
                  key: API_TOKEN
            - name: TABLE_NAME
              valueFrom:
                configMapKeyRef:
                  name: my-configmap
                  key: table
---
apiVersion: v1
kind: Service
metadata:
  name: ranking-s
  labels:
    app: ranking
spec:
  selector:
    app: ranking
  #clusterIP: None
  ports:
    - name: http
      protocol: TCP
      port: 5000
      targetPort: 5000
