apiVersion: apps/v1
kind: Deployment
metadata:
  name: airline-d
  labels:
    app: airline
spec:
  replicas: 3
  selector:
    matchLabels:
      app: airline
  template:
    metadata:
      labels:
        app: airline
    spec:
      containers:
      - name: airline
        image: therobertsan/airline-container
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: airline-s-n
  labels:
    app: airline
spec:
  type: NodePort
  selector:
    app: airline
  ports:
    - name: http
      protocol: TCP
      port: 5000
      nodePort: 30000
      targetPort: 5000
