apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin-d
  labels:
    app: admin
spec:
  replicas: 2
  selector:
    matchLabels:
      app: admin
  template:
    metadata:
      labels:
        app: admin
    spec:
      containers:
        - name: admin
          image: santig007/cnproject_54392
          ports:
            - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: admin-s-n
  labels:
    app: admin
spec:
  type: NodePort
  selector:
    app: admin
  ports:
    - name: http
      protocol: TCP
      port: 5000
      nodePort: 30000
      targetPort: 5000
