# This workflow will install Python dependencies, lint with a single version of Python, 
# build and push the image to DockerHub

name: Airlines Workflow

on:
  push:
    branches: 
    - main
    paths: 
    - src/airlines/**
    - k8s/deployments/airline-dep.yaml

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - 
      uses: actions/checkout@v3
    - 
      name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    # - 
    #   name: Install dependencies
    #   run: |
    #     python -m pip install --upgrade pip
    #     pip install flake8 pytest
    #     if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - 
      uses: mamba-org/setup-micromamba@v1
      with:
        environment-file: .config/env/dev-conda-env.yml
        # now called cache-environment
        cache-environment: true
    - 
      name: Initialize environment for bash
      run: |
        source "${{ env.CONDA_PREFIX }}/etc/profile.d/conda.sh"
        conda init bash
    - 
      name: Disable auto activation of base environment
      run: conda config --set auto_activate_base false
    # - 
    #   name: Lint with flake8
    #   run: |
    #     # stop the build if there are Python syntax errors or undefined names
    #     flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
    #     # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
    #     flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - 
      name: Test with pytest
      run: |
        pytest src/airlines/test_app.py
    -
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    -
      name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    -
      name: Build and push
      uses: docker/build-push-action@v4
      with:
        context: .
        file: ./src/airlines/Dockerfile
        tags: therobertsan/airline-container:v2
        push: true
        
